# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: remart_ex_dev
    ports:
      - 6543:5432
    volumes:
      - ./data:/var/lib/postgresql/data
